### ISSUE TITLE
Proposta de Projeto

### ISSUE THREAD

**Issue by claralimasilva** [atlantico-academy/equipe1-2024.1#1]
A etapa de entendimento de negócio se destina a compreensão dos objetivos e requisitos do projeto. 
- [x] Após compreender a tarefa a ser realizada na execução do projeto, modificar o arquivo `README.md`, contendo um resumo do projeto que será construído.
- [x] Apresentar uma justificativa para o projeto. 
- [x] É desejável que também se insira um [graphical abstract](https://www.elsevier.com/researcher/author/tools-and-resources/graphical-abstract).

**Comment by matt-balda** [comment]
@uSilas @claralimasilva revisar e complementar: o resumo e justificativa, produzido pelo @matheusvazdata no commit 5bf632a

**Comment by matt-balda** [comment]
Construir o **graphical abstract** após a conclusão das tasks e fechamento da issue #4
