### ISSUE TITLE
Exploração de dados

### ISSUE THREAD

**Issue by claralimasilva** [atlantico-academy/equipe1-2024.1#4]
- Criar um notebook de análise exploratória notebooks/01-exploratory_data_analysis.ipynb, contendo as seguintes seções de texto: 
- [x] Descrição dos dados, 
- [x] Perguntas de partida e hipóteses, 
- [x] Insights, de acordo com o conteúdo visto em aula;

**Comment by matt-balda** [comment]
#### Perguntas de partida e hipóteses, insights
- [x] 2 perguntas, gráficos para responder às perguntas e insights sobre - @uSilas 
- [x] 2 perguntas, gráficos para responder às perguntas e insights sobre - @claralimasilva 
- [x] 2 perguntas, gráficos para responder às perguntas e insights sobre - @matheusvazdata 
- [x] 2 perguntas, gráficos para responder às perguntas e insights sobre - @matt-balda
